# Generated by Django 3.1.7 on 2021-04-21 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobProfile',
            fields=[
                ('idno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=40)),
                ('username', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('idno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=40)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resume/')),
            ],
        ),
        migrations.CreateModel(
            name='TestOptions',
            fields=[
                ('qno', models.AutoField(primary_key=True, serialize=False)),
                ('choice', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='waste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.CharField(default=0, max_length=1)),
                ('b', models.CharField(default=0, max_length=1)),
                ('c', models.CharField(default=0, max_length=1)),
                ('d', models.CharField(default=0, max_length=1)),
                ('e', models.CharField(default=0, max_length=1)),
                ('f', models.CharField(default=0, max_length=1)),
                ('g', models.CharField(default=0, max_length=1)),
                ('h', models.CharField(default=0, max_length=1)),
                ('i', models.CharField(default=0, max_length=1)),
                ('j', models.CharField(default=0, max_length=1)),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Tesst', to='users.testoptions')),
            ],
        ),
        migrations.CreateModel(
            name='questions',
            fields=[
                ('idno', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('option1', models.CharField(max_length=100, null='true')),
                ('option2', models.CharField(max_length=100, null='true')),
                ('option3', models.CharField(max_length=100, null='true')),
                ('option4', models.CharField(max_length=100, null='true')),
                ('answer', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=1)),
                ('Subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Test', to='users.testoptions')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('mno', models.AutoField(primary_key=True, serialize=False)),
                ('mess', models.CharField(max_length=2000, null='true')),
                ('read', models.BooleanField(default=False)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Mreceiver', to='users.profile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Msender', to='users.profile')),
            ],
        ),
        migrations.CreateModel(
            name='JobPortal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(max_length=30)),
                ('jobDescription', models.TextField()),
                ('expectedSalary', models.CharField(blank=True, default='Declined to say', max_length=20)),
                ('is_verified', models.BooleanField(blank=True, default=False)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobp', to='users.jobprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Intrest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField(default=0)),
                ('category', models.CharField(blank=True, choices=[('Legendary', 'Legendary'), ('Titan', 'Titan'), ('Champion', 'Champion'), ('Master', 'Master'), ('Crystal', 'Crystal'), ('Gold', 'Gold'), ('Silver', 'Silver'), ('Bronze', 'Bronze')], max_length=10, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('Intrest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='int', to='users.testoptions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uuser', to='users.profile')),
            ],
        ),
        migrations.CreateModel(
            name='ConnectRequest',
            fields=[
                ('idno', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, choices=[('Accepted', 'Accepted'), ('Declined', 'Declined'), ('Pending', 'Pending')], max_length=10)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='users.profile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='users.profile')),
                ('sub', models.ForeignKey(null='true', on_delete=django.db.models.deletion.CASCADE, related_name='sub', to='users.testoptions')),
            ],
        ),
    ]
