# Generated by Django 3.1.7 on 2021-04-22 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_connectrequest_intrest_jobportal_jobprofile_message_profile_questions_testoptions_waste'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('Accepted', 'Accepted'), ('Declined', 'Declined'), ('Pending', 'Pending')], max_length=10)),
                ('Applicants', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicant', to='users.profile')),
                ('ApplyingTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='JobPortal', to='users.jobportal')),
            ],
        ),
    ]
