# Generated by Django 3.1.7 on 2021-04-22 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_applicants'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobportal',
            name='eyw_transactionref',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
