# Generated by Django 3.1.7 on 2021-04-22 09:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_jobportal_eyw_transactionref'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobportal',
            name='eyw_transactionref',
        ),
        migrations.AlterField(
            model_name='jobportal',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
