# Generated by Django 3.1.7 on 2021-04-25 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_applicants_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicants',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
