# Generated by Django 3.1.7 on 2021-04-25 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_applicants_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobportal',
            name='jTitle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobportal',
            name='noOfApplicants',
            field=models.TextField(blank=True, null=True),
        ),
    ]
