# Generated by Django 3.1.7 on 2021-04-25 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_jobportal_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobportal',
            name='noOfApplicants',
            field=models.TextField(blank=True, default=0, null=True),
        ),
    ]
