# Generated by Django 3.1.7 on 2021-04-26 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210425_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobportal',
            name='jTitle',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='jobportal',
            name='location',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jobportal',
            name='noOfApplicants',
            field=models.CharField(blank=True, default=0, max_length=10, null=True),
        ),
    ]
