# Generated by Django 3.1.7 on 2021-04-26 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20210426_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicants',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resume/%Y/%m/%d'),
        ),
    ]
