# Generated by Django 3.1.7 on 2021-04-26 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_applicants_xyz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicants',
            name='xyz',
        ),
    ]
