# Generated by Django 3.1.7 on 2021-04-27 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_remove_applicants_xyz'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dp',
            field=models.FileField(blank=True, null=True, upload_to='dp/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='dplink',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
