# Generated by Django 3.1.7 on 2021-04-28 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20210428_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='dp',
            field=models.FileField(blank=True, null=True, upload_to='dp/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='dplink',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
