# Generated by Django 3.1.7 on 2021-04-30 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20210430_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='dp',
            field=models.FileField(default='media/default.png', upload_to='dp/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='dplink',
            field=models.CharField(default='media/default.png', max_length=70),
        ),
        migrations.AlterField(
            model_name='jobportal',
            name='dp',
            field=models.FileField(default='media/default.png', upload_to='dp/'),
        ),
        migrations.AlterField(
            model_name='jobportal',
            name='dplink',
            field=models.CharField(default='media/default.png', max_length=70),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dp',
            field=models.FileField(default='media/default.png', upload_to='dp/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dplink',
            field=models.CharField(default='media/default.png', max_length=70),
        ),
    ]
