# Generated by Django 3.1.7 on 2021-04-30 15:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20210430_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobportal',
            name='jobDescription',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='mess',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
