# Generated by Django 3.1.7 on 2021-04-30 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20210430_1723'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DoomsdayCountdownTimer',
        ),
    ]
