# Generated by Django 3.1.7 on 2021-05-06 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_delete_doomsdaycountdowntimer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobportal',
            name='dp',
            field=models.FileField(default='https://visualpharm.com/assets/195/Company-595b40b75ba036ed117d5a01.svg', upload_to='dp/'),
        ),
        migrations.AlterField(
            model_name='jobportal',
            name='dplink',
            field=models.CharField(default='https://visualpharm.com/assets/195/Company-595b40b75ba036ed117d5a01.svg', max_length=70),
        ),
    ]
