# Generated by Django 3.1.7 on 2021-05-06 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_auto_20210506_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='dplink',
            field=models.CharField(default='/media/default.png', max_length=700),
        ),
        migrations.AlterField(
            model_name='jobportal',
            name='dplink',
            field=models.CharField(default='https://visualpharm.com/assets/195/Company-595b40b75ba036ed117d5a01.svg', max_length=700),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dplink',
            field=models.CharField(default='/media/default.png', max_length=700),
        ),
    ]
