# Generated by Django 3.1.7 on 2021-05-08 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_auto_20210506_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='dp',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='dplink',
        ),
    ]
