# Generated by Django 3.1.7 on 2021-05-08 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_auto_20210508_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dp',
            field=models.FileField(default='/media/default.png', upload_to='dp/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='dplink',
            field=models.CharField(default='/media/default.png', max_length=700),
        ),
    ]
